---
- name: manage nginx containers
  hosts: podman
  remote_user: testor
  become: false
  vars:
    params:
      - name: 'site1_server1'
      - name: 'site1_server2'
      - name: 'site1_server3'
      - name: 'site2_server1'
      - name: 'site2_server2'
      - name: 'site2_server3'



  tasks:
  - name: start nginx containers
    containers.podman.podman_containers:
      containers:    
        - name: "{{ item.name }}"
          image: docker.io/bitnami/nginx:latest
          state: stopped
    loop: "{{ params }}"
